name: Exhaustive Flake Test

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  check:
    name: Check Evaluation + Building
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v31.8.4
        with:
          extra_nix_config: |
            allow-import-from-derivation = false
            eval-cache = false
            experimental-features = flakes nix-command
            extra-experimental-features = pipe-operators

      - run:
          nix flake check